package io.github.eddytodd.bouncingballs.cli;
import io.github.eddytodd.bouncingballs.core.*;
import io.github.eddytodd.bouncingballs.resolver.*;
import io.github.eddytodd.bouncingballs.scheduler.*;
import java.nio.file.*;
import java.time.*;
import java.util.*;
/** Command line experiment runner. All durations are simulation seconds. */
public final class LabCli {
 public static void main(String[] args) throws Exception {Map<String,String>a=parse(args);if(args.length==0||a.containsKey("help")){help();return;}if(a.containsKey("list")){System.out.println("algorithms="+Arrays.toString(SchedulerKind.values())+"\nresolvers="+Arrays.toString(ResolverKind.values())+"\nworkloads="+Arrays.toString(Workloads.Kind.values()));return;}SchedulerKind sk=SchedulerKind.valueOf(a.getOrDefault("algorithm","GLOBAL_EVENT_QUEUE").toUpperCase());ResolverKind rk=ResolverKind.valueOf(a.getOrDefault("resolver","ITERATIVE").toUpperCase());Workloads.Kind wk=Workloads.Kind.valueOf(a.getOrDefault("workload","SPARSE_UNIFORM").toUpperCase());int count=Integer.parseInt(a.getOrDefault("balls","100"));long seed=Long.parseLong(a.getOrDefault("seed","1"));double restitution=Double.parseDouble(a.getOrDefault("restitution","1"));double duration=Double.parseDouble(a.getOrDefault("duration","1"));long events=Long.parseLong(a.getOrDefault("events","100000"));Workloads.Setup setup=Workloads.create(wk,count,seed,restitution);Simulation s=new Simulation(setup.balls(),setup.bounds(),new SimulationConfig(sk,rk,NumericalPolicy.DEFAULT,Double.parseDouble(a.getOrDefault("step","0.001"))));long start=System.nanoTime();s.advance(duration,events);long elapsed=System.nanoTime()-start;String result=json(sk,rk,wk,count,seed,restitution,duration,s,elapsed);System.out.println(result);String out=a.get("out");if(out!=null)Files.writeString(Path.of(out),result+System.lineSeparator(),StandardOpenOption.CREATE,StandardOpenOption.APPEND);}
 private static Map<String,String> parse(String[] xs){Map<String,String>m=new HashMap<>();for(int i=0;i<xs.length;i++)if(xs[i].startsWith("--")){String k=xs[i].substring(2);m.put(k,i+1<xs.length&&!xs[i+1].startsWith("--")?xs[++i]:"true");}return m;}
 private static String json(SchedulerKind a,ResolverKind r,Workloads.Kind w,int n,long seed,double e,double duration,Simulation s,long nanos){SimulationStats z=s.stats();return String.format(Locale.ROOT,"{\"timestamp\":\"%s\",\"algorithm\":\"%s\",\"resolver\":\"%s\",\"workload\":\"%s\",\"balls\":%d,\"seed\":%d,\"restitution\":%.6f,\"requestedSeconds\":%.6f,\"simulatedSeconds\":%.12f,\"elapsedNanos\":%d,\"resolvedContacts\":%d,\"toiQueries\":%d,\"candidateChecks\":%d,\"queuePushes\":%d,\"queuePops\":%d,\"staleEvents\":%d,\"stalePercent\":%.4f,\"predictionRecomputations\":%d,\"dependencyInvalidations\":%d}",Instant.now(),a,r,w,n,seed,e,duration,s.time(),nanos,z.resolvedContacts,z.toiQueries,z.candidateChecks,z.queuePushes,z.queuePops,z.staleEvents,z.stalePercent(),z.predictionRecomputations,z.dependencyInvalidations);}
 private static void help(){System.out.println("Usage: LabCli --algorithm GLOBAL_EVENT_QUEUE --resolver ITERATIVE --workload SPARSE_UNIFORM --balls 100 --duration 1 --events 100000 --seed 1 --restitution 1 --out result.json\nUse --list to enumerate modes.");}
}
