package io.github.eddytodd.bouncingballs.core;
import io.github.eddytodd.bouncingballs.resolver.*;
import io.github.eddytodd.bouncingballs.scheduler.*;
import java.util.*;

/** Rendering-free deterministic event simulation. Calls to advance are explicit simulation-time operations. */
public final class Simulation {
 private final List<Ball> balls; private final Bounds bounds; private final SimulationConfig config; private final SimulationStats stats=new SimulationStats(); private final EventScheduler scheduler; private final ContactResolver resolver; private double time;
 public Simulation(List<Ball> balls,Bounds bounds,SimulationConfig config){this.balls=List.copyOf(balls);this.bounds=bounds;this.config=config;this.scheduler=switch(config.scheduler()){case ALL_PAIRS_CCD->new AllPairsCcdScheduler();case GLOBAL_EVENT_QUEUE->new GlobalEventQueueScheduler();case COMPUTE_AHEAD_DEPENDENCY_QUEUE->new ComputeAheadDependencyQueue();case DISCRETE_BASELINE->null;};this.resolver=switch(config.resolver()){case SEQUENTIAL->new SequentialResolver();case ITERATIVE->new IterativeIslandResolver(96,config.numericalPolicy().tolerance(1));case DIRECT->new DirectIslandResolver();};if(scheduler!=null)scheduler.rebuild(this.balls,bounds,config.numericalPolicy(),stats);}
 public List<Ball> balls(){return balls;} public double time(){return time;} public SimulationStats stats(){return stats;}
 public void advance(double duration,long maxEvents){if(duration<0||maxEvents<0)throw new IllegalArgumentException("negative limit");if(config.scheduler()==SchedulerKind.DISCRETE_BASELINE){discrete(duration,maxEvents);return;}double remaining=duration;long events=0;int zeros=0;while(remaining>config.numericalPolicy().tolerance(remaining)&&events<maxEvents){List<CollisionEvent> batch=scheduler.nextBatch(config.numericalPolicy(),stats);if(batch.isEmpty()){advanceBodies(remaining);scheduler.timeAdvanced(remaining);time+=remaining;return;}double dt=batch.get(0).time()-time;if(dt>remaining){advanceBodies(remaining);scheduler.timeAdvanced(remaining);time+=remaining;return;}if(dt<0)dt=0;advanceBodies(dt);scheduler.timeAdvanced(dt);time+=dt;remaining-=dt;List<Contact> contacts=contacts(batch);Set<Ball> changed=new HashSet<>();for(CollisionEvent e:batch){changed.add(e.a());if(e.b()!=null)changed.add(e.b());}resolveIslands(contacts);for(Ball b:changed)b.generation++;scheduler.trajectoriesChanged(changed,balls,bounds,config.numericalPolicy(),stats);events+=batch.size();if(dt<=config.numericalPolicy().tolerance(time)){if(++zeros>config.numericalPolicy().maxZeroTimeBatches())throw new IllegalStateException("zero-time contact loop; see SimulationStats.zeroTimeBatches");stats.zeroTimeBatches++;}else zeros=0;}}
 private void discrete(double duration,long max){double left=duration;long n=0;while(left>0&&n<max){double dt=Math.min(left,config.discreteStep());advanceBodies(dt);time+=dt;left-=dt;List<Contact> c=new ArrayList<>();for(int i=0;i<balls.size();i++)for(int j=i+1;j<balls.size();j++){Ball a=balls.get(i),b=balls.get(j);double x=a.position.x-b.position.x,y=a.position.y-b.position.y,r=a.radius+b.radius;if(x*x+y*y<=r*r)c.add(ballContact(a,b));}resolveIslands(c);n+=c.size();}}
 private void advanceBodies(double dt){for(Ball b:balls)b.advance(dt);}
 private List<Contact> contacts(List<CollisionEvent> events){Map<String,Contact> unique=new TreeMap<>();for(CollisionEvent e:events){Contact c=e.isWall()?wallContact(e.a(),e.wall()):ballContact(e.a(),e.b());if(c.normalVelocity()<=config.numericalPolicy().tolerance(1))unique.putIfAbsent(e.isWall()?"w"+e.a().id+":"+e.wall():"b"+Math.min(e.a().id,e.b().id)+":"+Math.max(e.a().id,e.b().id),c);}return new ArrayList<>(unique.values());}
 private Contact ballContact(Ball a,Ball b){double x=a.position.x-b.position.x,y=a.position.y-b.position.y,d=Math.hypot(x,y);if(d==0){x=a.id<b.id?1:-1;y=0;d=1;}return new Contact(a,b,x/d,y/d,Math.min(a.restitution,b.restitution),Math.min(a.id,b.id)*1_000_000+Math.max(a.id,b.id));}
 private Contact wallContact(Ball a,int w){double nx=(w==CollisionEvent.LEFT?1:w==CollisionEvent.RIGHT?-1:0),ny=(w==CollisionEvent.BOTTOM?1:w==CollisionEvent.TOP?-1:0);return new Contact(a,null,nx,ny,a.restitution,10_000_000+a.id*4+w);}
 private void resolveIslands(List<Contact> contacts){Map<Ball,List<Contact>> by=new HashMap<>();for(Contact c:contacts){by.computeIfAbsent(c.a(),x->new ArrayList<>()).add(c);if(c.b()!=null)by.computeIfAbsent(c.b(),x->new ArrayList<>()).add(c);}Set<Contact> seen=Collections.newSetFromMap(new IdentityHashMap<>());for(Contact start:contacts)if(seen.add(start)){List<Contact> island=new ArrayList<>();Deque<Contact> q=new ArrayDeque<>();q.add(start);while(!q.isEmpty()){Contact c=q.remove();island.add(c);for(Ball b:List.of(c.a(),c.b()==null?c.a():c.b()))for(Contact next:by.getOrDefault(b,List.of()))if(seen.add(next))q.add(next);}resolver.resolve(island,stats);}}
}
